### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by dblock** [opensearch-project/notifications#358] opened 2021-10-27 13:41 UTC
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/95, add Windows support.

- [ ] Passing CI on Windows
- [ ] Documentation

**Comment by dblock** [comment] 2021-10-30 01:10
Adding Windows CI will ensure that the plugin actually works on Windows, we can't assume that it works because it's theoretically portable.

**Comment by bbarani** [comment] 2022-10-26 20:10
@praveensameneni @qreshi Can you please update the status?

**Comment by qreshi** [comment] 2022-10-31 16:17
I've drafted a [PR](https://github.com/opensearch-project/notifications/pull/557) for this, however, there are currently some failures that are being investigated:

1. The `integTest` and `jacocoTestReport` task need to be skipped for `windows` as it faces failures otherwise. For some reason though I'm still seeing these tasks being called even with `-x integTest -x jacocoTestReport`
2. There are some failures for the OSD Notifications build GitHub CI as well because it is complaining about some of the Unix commands that were being run not being available for the other OS environments. This can be investigated after the first issue is resolved since this task needs the backend plugin running successfully

**Comment by qreshi** [comment] 2022-11-01 16:48
An update, the issues above have been circumvented (among others) and currently the issues with the PR are:

1. The backend workflow is for the most part successful but there are some test failures for the Windows run, we'll need to see if this is a flakey test or if there is a failure for some cases based on the platform
2. The Notifications Dashboards workflow is hitting some errors when running the unit or Cypress tests due to build scripts not executing as intended on the Windows platform

I'm currently looking into the second issue first since I'd like all the CIs to at least run the tests first so we can verify if the tests are failing because of the difference in platform.

**Comment by qreshi** [comment] 2022-11-04 21:47
The related PR has Cypress tests running for Windows, however, there is Cypress flakiness (and general issues with GitHub containers) that is not Windows specific causing test to fail sometimes. The general state of the PR is summarized [in this comment](https://github.com/opensearch-project/notifications/pull/557#issuecomment-1304106178).

We can close out this issue after the PR is merged in but we'll be following up on the general test flakiness as a follow-up.

**Closed** 2022-11-05 06:25 UTC
Labels: windows, v2.4.0
